name: CD - Azure WebApp (Containers)

on:
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: 'Image repository name'
        required: true
        default: 'api-medical'
      IMAGE_TAG:
        description: 'Image tag'
        required: true
        default: 'latest'
      AZURE_WEBAPP_NAME:
        description: 'Azure WebApp name'
        required: true
      PORT:
        description: 'Application port'
        default: '443'
        required: true

env:
  IMAGE_FULL_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.inputs.IMAGE_REPOSITORY }}:${{ github.event.inputs.IMAGE_TAG }}

jobs:

  build_push:
    name: Build & Push Container Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate with Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          tags: ${{ env.IMAGE_FULL_NAME }}
          push: true


  deploy:
    name: Deploy to Azure WebApp (Container)
    runs-on: ubuntu-latest
    needs: build_push

    steps:
      - name: Publish container to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.AZURE_WEBAPP_NAME }}
          images: ${{ env.IMAGE_FULL_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_JHOAN }}


  test:
    name: Run Post-Deployment API Tests
    runs-on: ubuntu-latest
    needs: [build_push, deploy]

    steps:
      - name: Checkout hurl test file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            session.hurl
          sparse-checkout-cone-mode: false

      - name: Install Hurl testing tool
        uses: gacts/install-hurl@v1

      - name: Execute Hurl tests
        run: |
          hurl \
            --variable host=https://${{ github.event.inputs.AZURE_WEBAPP_NAME }}.azurewebsites.net \
            --connect-timeout 20s \
            --error-format long \
            --verbose \
            --test session.hurl
