name: Azure Continuous Delivery Jhoan

on:
  workflow_dispatch:
    inputs:
      IMAGE_REPOSITORY:
        description: 'Repository of the image'
        required: true
        default: 'api-medical'
      IMAGE_TAG:
        description: 'Tag of the image'
        required: true
        default: 'latest'
      AZURE_WEBAPP_NAME:
        description: 'Nombre del App Service creado en Azure'
        required: true
      PORT:
        description: 'Port of the application'
        default: '443'
        required: true

env:
  IMAGE_FULL_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.inputs.IMAGE_REPOSITORY }}:${{ github.event.inputs.IMAGE_TAG }}

jobs:
  build-and-push-image:
    name: Build and Push to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_FULL_NAME }}

  deploy:
    name: Deploy container to Azure WebApp
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Deploy using publish profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ github.event.inputs.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_JHOAN }}
          images: ${{ env.IMAGE_FULL_NAME }}

  test-deploy:
    name: Run API tests using Hurl
    runs-on: ubuntu-latest
    needs: [build-and-push-image, deploy]

    steps:
      - name: Checkout Hurl file
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            session.hurl
          sparse-checkout-cone-mode: false

      - name: Install Hurl
        uses: gacts/install-hurl@v1

      - name: Test API
        run: hurl --variable host=https://${{ github.event.inputs.AZURE_WEBAPP_NAME }}.azurewebsites.net --connect-timeout 20s --error-format long --verbose --test session.hurl
